### PR TITLE
Show attachments as blocks instead of list to allow enhanced actions

### LINKED ISSUE #1308: Ability to open attachments directly
In most scenarios, you simply want to open an attachment without saving it. Currently it's only possible to either download the file locally or save it to the ownCloud file system. Attachments should be opened by the browser when clicking onto it. Preferably another tab is used so the user does not navigate away.

### Steps to reproduce
1. open a mail with attachments
2. click on the attachment (name)

### Expected behaviour
The browser should open the file

### Actual behaviour
nothing

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31044685-ability-to-open-attachments-directly?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1437: Error while saving the attachements to owncloud
While saving attachements I received directly to owncloud I get an error 500. 
I use core from master and mail 0.4.2
```
OCP\AppFramework\Db\DoesNotExistException: Unable to load the attachment.
	/usr/share/webapps/owncloud/apps/mail/lib/attachment.php - line 44: OCA\Mail\Attachment->load()
	/usr/share/webapps/owncloud/apps/mail/lib/mailbox.php - line 361: OCA\Mail\Attachment->__construct(Object(Horde_Imap_Client_Socket), Object(Horde_Imap_Client_Mailbox), '153', '{attachmentId}')
	/usr/share/webapps/owncloud/apps/mail/lib/controller/messagescontroller.php - line 294: OCA\Mail\Mailbox->getAttachment('153', '{attachmentId}')
	[internal function] OCA\Mail\Controller\MessagesController->saveAttachment(2, 'SU5CT1g=', '153', '{attachmentId}', '/Documents/')
	/usr/share/webapps/owncloud/lib/private/appframework/http/dispatcher.php - line 159: call_user_func_array(Array, Array)
	/usr/share/webapps/owncloud/lib/private/appframework/http/dispatcher.php - line 89: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'saveAttachment')
	/usr/share/webapps/owncloud/lib/private/appframework/app.php - line 110: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'saveAttachment')
	/usr/share/webapps/owncloud/lib/private/appframework/routing/routeactionhandler.php - line 45: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'saveAttachment', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
	[internal function] OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
	/usr/share/webapps/owncloud/lib/private/route/router.php - line 276: call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
	/usr/share/webapps/owncloud/lib/base.php - line 882: OC\Route\Router->match('/apps/mail/acco...')
	/usr/share/webapps/owncloud/index.php - line 39: OC handleRequest()
	{main}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33159685-error-while-saving-the-attachements-to-owncloud?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChristophWurst**
This moves attachment rendering out of the message view and shows attachment as blocks instead of a simple list:
bildschirmfoto von 2016-04-24 15-48-31

My goal is to make the attachments view ready for enhanced attachment actions, like integration with other apps (contacts, calendar, maps) and previews of other file types (ref #1374, #79).

TODO:
- [x] fix single attachment
- [x] make attachment width responsive (on mobile there should be only a single attachment per line)
- [x] rebase onto #1447 once it's merged so the save-attachment-methods can be moved into the attachment(s) view
- [x] show attachments with previews first? cc @jancborchardt (is done [by the server](https://github.com/owncloud/mail/blob/master/lib/controller/messagescontroller.php#L470-L479) already)
- [x] show full attachment name on hover
- [x] open attachment on click (ref #1308)
- [x] fix 'save to cloud' urls (fixes #1437)
- [x] find out while core failes saving the files – it failed only on my dev instance apparently

Ideas for future PRs:
- use popover for download and other attachment actions

fixes #1308

### CODE REVIEW

**Comment by jancborchardt** [comment]
This looks super nice! :+1: 

> show attachments with previews first?

Yeah, good call.

File: js/service/attachmentservice.js [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+			'apps/mail/accounts/{accountId}/' +
+			'folders/{folderId}/messages/{messageId}/' +
+			'attachment/{attachmentId}', {
+				accountId: account.get('accountId'),
+				folderId: folder.get('id'),
+				messageId: messageId,
+				attachmentId: attachmentId
+			});
+		console.log(arguments);
+		console.log(url);
```
Comment (ChristophWurst) [inline js/service/attachmentservice.js]: - [ ] TODO: remove

File: js/service/attachmentservice.js [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+			type: 'POST',
+			success: function() {
+				defer.resolve();
+			},
+			error: function() {
+				defer.reject();
+			}
+		};
+
+		console.log('now');
```
Comment (ChristophWurst) [inline js/service/attachmentservice.js]: - [ ] TODO: remove

**Comment by skjnldsv** [comment]
Can't save on my owncloud file:
```
Error	index	OCP\Lock\LockedException: "Site.zip" is locked
/usr/share/webapps/owncloud/lib/private/files/view.php - line 1085: OC\Files\View-changeLock('/admin/files/Si...', 1)
/usr/share/webapps/owncloud/lib/private/files/view.php - line 506: OC\Files\View-basicOperation('touch', '/admin/files/Si...', Array, NULL)
/usr/share/webapps/owncloud/lib/private/files/node/folder.php - line 165: OC\Files\View-touch('/admin/files/Si...')
/usr/share/webapps/owncloud/apps/mail/lib/controller/messagescontroller.php - line 307: OC\Files\Node\Folder->newFile('//Site.zip')
[internal function] OCA\Mail\Controller\MessagesController->saveAttachment(2, 'QXJjaGl2ZXM=', '50', 2, '/')
/usr/share/webapps/owncloud/lib/private/appframework/http/dispatcher.php - line 159: call_user_func_array(Array, Array)
/usr/share/webapps/owncloud/lib/private/appframework/http/dispatcher.php - line 89: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'saveAttachment')
/usr/share/webapps/owncloud/lib/private/appframework/app.php - line 110: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'saveAttachment')
/usr/share/webapps/owncloud/lib/private/appframework/routing/routeactionhandler.php - line 45: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'saveAttachment', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
/usr/share/webapps/owncloud/lib/private/route/router.php - line 276: call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
/usr/share/webapps/owncloud/lib/base.php - line 882: OC\Route\Router->match('/apps/mail/acco...')
/usr/share/webapps/owncloud/index.php - line 39: OC handleRequest()
{main}
```

**Comment by skjnldsv** [comment]
Except from that, it's working great. Congrats on using inline-block, good call!

**Comment by ChristophWurst** [comment]
@skjnldsv could you please open a new issue for that bug? Seems unrelated, but we should definitely fix that too!
